"""
Orchestrates: Nosana (plan code) -> Neo4j (facilities) -> Daytona (execute) -> Neo4j (cascade) -> Nosana (brief).
Yields JSON-serialisable events so the UI can narrate each sponsor platform live.
"""
from __future__ import annotations

import base64
import time
from typing import Iterator

from . import config, graph, llm, sandbox


def _ev(platform: str, status: str, msg: str, **data) -> dict:
    return {"t": round(time.time(), 3), "platform": platform, "status": status, "msg": msg, **data}


def run_query(query: str) -> Iterator[dict]:
    t0 = time.time()
    yield _ev("agent", "start", f"query: {query}",
              flags={"nosana": config.USE_NOSANA, "daytona": config.USE_DAYTONA, "neo4j": config.USE_NEO4J})

    # 1. plan code (LLM on Nosana)
    yield _ev("nosana", "start", "asking the model to write the GIS script…")
    provider, script, fallback = llm.plan_script(query)
    yield _ev("nosana", "fallback" if fallback else "ok",
              f"script generated by {provider} ({len(script.splitlines())} lines)", code=script)

    # 2. facilities from graph
    logs: list[str] = []
    g = graph.connect(logs.append)
    for l in logs:
        yield _ev("neo4j", "ok" if g.provider == "neo4j" else "fallback", l)
    logs.clear()
    g.seed(logs.append)
    facilities = g.facilities()
    for l in logs:
        yield _ev("neo4j", "ok" if g.provider == "neo4j" else "fallback", l)
    yield _ev("neo4j", "ok", f"loaded {len(facilities)} facilities for spatial test")

    # 3. execute in sandbox (Daytona)
    yield _ev("daytona", "start", "spinning up isolated sandbox…")
    events: list[dict] = []

    def slog(m: str):
        events.append(_ev("daytona", "log", m))

    try:
        sb = sandbox.run(script, facilities, slog)
    except Exception as e:  # noqa: BLE001
        for e_ in events:
            yield e_
        yield _ev("daytona", "error", f"execution failed: {e}")
        return
    for e_ in events:
        yield e_
    res = sb["result"]
    yield _ev("daytona", "ok" if sb["provider"] == "daytona" else "fallback",
              f"{sb['provider']}: flooded {res['flooded_area_km2']} km² "
              f"({res['dem_source']}, {res['elapsed_s']}s in sandbox)",
              stats={k: res[k] for k in ("area_name", "water_level_m", "flooded_area_km2",
                                          "flooded_fraction", "dem_source", "dem_shape", "min_elev_m")})

    # 4. write scenario + cascade query (Neo4j)
    yield _ev("neo4j", "start", "writing scenario & running cascade query…")
    logs.clear()
    sid = g.write_scenario(res, logs.append)
    for l in logs:
        yield _ev("neo4j", "ok" if g.provider == "neo4j" else "fallback", l)
    cascade = g.cascade(sid)
    yield _ev("neo4j", "ok" if g.provider == "neo4j" else "fallback",
              f"cascade query: {len(cascade)} facilities outside the water lose power",
              cypher=graph.CASCADE_CYPHER.strip(), cascade=cascade, scenario_id=sid)
    g.close()

    # 5. briefing (LLM on Nosana)
    yield _ev("nosana", "start", "drafting Japanese briefing…")
    sprov, brief = llm.summarize(res, cascade)
    yield _ev("nosana", "ok" if sprov == "nosana" else "fallback", f"briefing by {sprov}", briefing=brief)

    yield _ev("agent", "done", f"finished in {time.time() - t0:.1f}s",
              map_png_b64=base64.b64encode(sb["map_png"]).decode() if sb["map_png"] else None,
              facilities=res["facilities"], flooded_ids=res["flooded_facility_ids"],
              cascade=cascade, briefing=brief, code=script, scenario_id=sid,
              providers={"llm": provider, "sandbox": sb["provider"], "graph": g.provider})
